data:extend({
    {
        type = "module",
        name = "sifter-module-1",
        icon = "__base__/graphics/icons/productivity-module.png",
        icon_size = 64,
        category = "productivity",
        tier = 1,
        effect = { productivity = {bonus = 1}},
        limitation = {"ab-mineral-cyclone", "ab-waste-cyclone", "ab-slush-filtration", "ab-ore-slurry-refining", "ab-ore-concentrate-refining"},
        limitation_message_key = "This is not a compatible Sifting recipe",
        subgroup = "module",
        order = "c[productivity]-a[stream-sifter-productivity-module]",
        stack_size = 50
    },
    {
        type = "module",
        name = "arboretum-module-1",
        icon = "__base__/graphics/icons/productivity-module.png",
        icon_size = 64,
        category = "productivity",
        tier = 1,
        effect = { productivity = {bonus = 2}},
        limitation = {},
        limitation_message_key = "This is not growing a tree, try another recipe!",
        subgroup = "module",
        order = "c[productivity]-a[arboretum-productivity-module]",
        stack_size = 50
    },
    {
        type = "module",
        name = "efficient-breeding-processor",
        icon = "__base__/graphics/icons/speed-module.png",
        icon_size = 64,
        category = "productivity",
        tier = 1,
        effect = { speed = {bonus = 0.25}},
        limitation = {
            "ac-breed-glowfin-trenchers",
            "ac-breed-glowfin-trenchers-egg",
            "ac-process-glowfin-trenchers-eggs-for-fish",
            "ac-breed-mukmoux",
            "ac-breed-mukmoux-egg",
            "ac-process-mukmoux-eggs-for-fish",
            "ac-breed-silverscale-glider",
            "ac-breed-silverscale-glider-egg",
            "ac-process-silverscale-glider-eggs-for-fish",
            "ac-breed-spiral-shellfish",
            "ac-breed-spiral-shellfish-egg",
            "ac-process-spiral-shellfish-eggs-for-fish",
            "ac-breed-silent-drifter",
            "ac-breed-silent-drifter-egg",
            "ac-process-silent-drifter-eggs-for-fish",
            "ac-breed-neon-nocturne",
            "ac-breed-neon-nocturne-egg",
            "ac-process-neon-nocturne-eggs-for-fish",
            "ac-breed-starfin-darters",
            "ac-breed-starfin-darters-egg",
            "ac-process-starfin-darters-eggs-for-fish",
            "ac-breed-stream-sifter",
            "ac-breed-stream-sifter-egg",
            "ac-process-stream-sifter-eggs-for-fish",
            "ac-breed-twilight-tetra",
            "ac-breed-twilight-tetra-egg",
            "ac-process-twilight-tetra-eggs-for-fish",
            "consume-fertilizer",
        },
        limitation_message_key = "This is not a compatible breeding recipe",
        subgroup = "module",
        order = "c[speed]-a[efficient-breeding-processor]",
        stack_size = 50
    },
    --Efficient Egg Gathering
    {
        type = "module",
        name = "efficient-egg-gathering-processor",
        icon = "__base__/graphics/icons/productivity-module.png",
        icon_size = 64,
        category = "productivity",
        tier = 1,
        effect = { productivity = {bonus = 0.5}},
        limitation = {
            "ac-breed-glowfin-trenchers",
            "ac-breed-glowfin-trenchers-egg",
            "ac-process-glowfin-trenchers-eggs-for-fish",
            "ac-breed-mukmoux",
            "ac-breed-mukmoux-egg",
            "ac-process-mukmoux-eggs-for-fish",
            "ac-breed-silverscale-glider",
            "ac-breed-silverscale-glider-egg",
            "ac-process-silverscale-glider-eggs-for-fish",
            "ac-breed-spiral-shellfish",
            "ac-breed-spiral-shellfish-egg",
            "ac-process-spiral-shellfish-eggs-for-fish",
            "ac-breed-silent-drifter",
            "ac-breed-silent-drifter-egg",
            "ac-process-silent-drifter-eggs-for-fish",
            "ac-breed-neon-nocturne",
            "ac-breed-neon-nocturne-egg",
            "ac-process-neon-nocturne-eggs-for-fish",
            "ac-breed-starfin-darters",
            "ac-breed-starfin-darters-egg",
            "ac-process-starfin-darters-eggs-for-fish",
            "ac-breed-stream-sifter",
            "ac-breed-stream-sifter-egg",
            "ac-process-stream-sifter-eggs-for-fish",
            "ac-breed-twilight-tetra",
            "ac-breed-twilight-tetra-egg",
            "ac-process-twilight-tetra-eggs-for-fish",
            "consume-fertilizer",
        },
        limitation_message_key = "This is not a compatible breeding recipe",
        subgroup = "module",
        order = "c[productivity]-a[efficient-egg-gathering-processor]",
        stack_size = 50
    },
})
